## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Robles Brothers"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  turno = "https://app.turno.com/vacation-rental-cleaner-profile/521733/417844/Moreno%20Valley/California/United%20States"
  nextdoor = "https://nextdoor.com/page/robles-brothers-cleaning"
  email = "roblesbrotherscleaning@gmail.com"
  instagram = "https://instagram.com"
  thumbtack = "https://www.thumbtack.com/ca/moreno-valley/house-cleaning/robles-brothers-cleaning/service/546050796414271488"
  telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]